Fix parse

diff --git a/.github/workflows/build_tgui.yml b/.github/workflows/build_tgui.yml
--- a/.github/workflows/build_tgui.yml
+++ b/.github/workflows/build_tgui.yml
@@ -79,7 +79,11 @@ jobs:
             -H "Accept: application/vnd.github+json" \
             -H "X-GitHub-Api-Version: 2022-11-28" \
             "https://api.github.com/repos/$REPOSITORY/compare/$DEFAULT_BRANCH...$CURRENT_BRANCH")
-          read -r behind_by ahead_by <<<$(jq '.behind_by, .ahead_by' <<<$compare_result)
+          # Assign multiple variables with one jq execution
+          if IFS=$'\n' read -d '' -r behind_by ahead_by <<<$(jq '.behind_by, .ahead_by' <<<$compare_result) ; [ -z "$behind_by" ] || [ -z "$ahead_by" ] ; then
+            echo '- Unable to determine the distance between the HEAD branch and the default branch.' | tee -a "$GITHUB_STEP_SUMMARY"
+            exit 1
+          fi
           if [ "$behind_by" -le 0 ] ; then
             echo '- Skipping merge. Up-to-date with default branch.' | tee -a "$GITHUB_STEP_SUMMARY"
             exit 0
